# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jason/Dev/TaosData

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jason/Dev/TaosData

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.15.3/bin/cpack --config ./CPackSourceConfig.cmake /Users/jason/Dev/TaosData/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.15.3/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jason/Dev/TaosData/CMakeFiles /Users/jason/Dev/TaosData/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jason/Dev/TaosData/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named os

# Build rule for target.
os: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os
.PHONY : os

# fast build rule for target.
os/fast:
	$(MAKE) -f src/os/darwin/CMakeFiles/os.dir/build.make src/os/darwin/CMakeFiles/os.dir/build
.PHONY : os/fast

#=============================================================================
# Target rules for targets named tutil

# Build rule for target.
tutil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tutil
.PHONY : tutil

# fast build rule for target.
tutil/fast:
	$(MAKE) -f src/util/CMakeFiles/tutil.dir/build.make src/util/CMakeFiles/tutil.dir/build
.PHONY : tutil/fast

#=============================================================================
# Target rules for targets named trpc

# Build rule for target.
trpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trpc
.PHONY : trpc

# fast build rule for target.
trpc/fast:
	$(MAKE) -f src/rpc/CMakeFiles/trpc.dir/build.make src/rpc/CMakeFiles/trpc.dir/build
.PHONY : trpc/fast

#=============================================================================
# Target rules for targets named taos

# Build rule for target.
taos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taos
.PHONY : taos

# fast build rule for target.
taos/fast:
	$(MAKE) -f src/client/CMakeFiles/taos.dir/build.make src/client/CMakeFiles/taos.dir/build
.PHONY : taos/fast

#=============================================================================
# Target rules for targets named taos_static

# Build rule for target.
taos_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taos_static
.PHONY : taos_static

# fast build rule for target.
taos_static/fast:
	$(MAKE) -f src/client/CMakeFiles/taos_static.dir/build.make src/client/CMakeFiles/taos_static.dir/build
.PHONY : taos_static/fast

#=============================================================================
# Target rules for targets named shell

# Build rule for target.
shell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shell
.PHONY : shell

# fast build rule for target.
shell/fast:
	$(MAKE) -f src/kit/shell/CMakeFiles/shell.dir/build.make src/kit/shell/CMakeFiles/shell.dir/build
.PHONY : shell/fast

#=============================================================================
# Target rules for targets named sdb

# Build rule for target.
sdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdb
.PHONY : sdb

# fast build rule for target.
sdb/fast:
	$(MAKE) -f src/sdb/CMakeFiles/sdb.dir/build.make src/sdb/CMakeFiles/sdb.dir/build
.PHONY : sdb/fast

#=============================================================================
# Target rules for targets named monitor

# Build rule for target.
monitor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monitor
.PHONY : monitor

# fast build rule for target.
monitor/fast:
	$(MAKE) -f src/modules/monitor/CMakeFiles/monitor.dir/build.make src/modules/monitor/CMakeFiles/monitor.dir/build
.PHONY : monitor/fast

#=============================================================================
# Target rules for targets named http

# Build rule for target.
http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http
.PHONY : http

# fast build rule for target.
http/fast:
	$(MAKE) -f src/modules/http/CMakeFiles/http.dir/build.make src/modules/http/CMakeFiles/http.dir/build
.PHONY : http/fast

#=============================================================================
# Target rules for targets named taosd

# Build rule for target.
taosd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taosd
.PHONY : taosd

# fast build rule for target.
taosd/fast:
	$(MAKE) -f src/system/CMakeFiles/taosd.dir/build.make src/system/CMakeFiles/taosd.dir/build
.PHONY : taosd/fast

#=============================================================================
# Target rules for targets named prepare_env_target

# Build rule for target.
prepare_env_target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prepare_env_target
.PHONY : prepare_env_target

# fast build rule for target.
prepare_env_target/fast:
	$(MAKE) -f src/system/CMakeFiles/prepare_env_target.dir/build.make src/system/CMakeFiles/prepare_env_target.dir/build
.PHONY : prepare_env_target/fast

#=============================================================================
# Target rules for targets named jdbc_target

# Build rule for target.
jdbc_target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jdbc_target
.PHONY : jdbc_target

# fast build rule for target.
jdbc_target/fast:
	$(MAKE) -f src/connector/jdbc/CMakeFiles/jdbc_target.dir/build.make src/connector/jdbc/CMakeFiles/jdbc_target.dir/build
.PHONY : jdbc_target/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... package"
	@echo "... os"
	@echo "... tutil"
	@echo "... trpc"
	@echo "... taos"
	@echo "... taos_static"
	@echo "... shell"
	@echo "... sdb"
	@echo "... monitor"
	@echo "... http"
	@echo "... taosd"
	@echo "... prepare_env_target"
	@echo "... jdbc_target"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

